### ISSUE TITLE
mp2rage_denoise.py input error

### ISSUE THREAD

**Issue by pesojka** [MICA-MNI/micapipe#146]
Hello,
it seems that mp2rage_denoise.py takes as input T1w image instead of UNI image. This leads to the following error:

COMMAND -->   /opt/micapipe/functions/mp2rage_denoise.py /tmp/6194_micapipe_proc_struc-vol_F113/sub-F113_ses-01_space-nativepro_T1w_reo.nii.gz /bids_dataset/sub-F113/ses-01/anat/sub-F113_ses-01_acq-inv1_T1map.nii.gz /bids_dataset/sub-F113/ses-01/anat/sub-F113_ses-01_acq-inv2_T1map.nii.gz /tmp/6194_micapipe_proc_struc-vol_F113/sub-F113_ses-01_space-nativepro_T1w_n4.nii.gz --mf 45
Traceback (most recent call last):
  File "/opt/micapipe/functions/mp2rage_denoise.py", line 130, in <module>
    mp2rage_robust_combination(params.uni,params.inv1,params.inv2,filename_output=params.output,multiplying_factor=params.mf)
  File "/opt/micapipe/functions/mp2rage_denoise.py", line 69, in mp2rage_robust_combination
    image_inv1_fdata = np.sign(image_uni_fdata) * image_inv1_fdata
ValueError: operands could not be broadcast together with shapes (176,240,256) (224,240,256)

In my case, INV1, INV2 and UNI have 224,240,256 dimensions but T1w has 176,240,256 dims

files in the anat folder:
sub-F113_ses-01_acq-inv2_T1map.json
sub-F113_ses-01_acq-inv2_T1map.nii.gz
sub-F113_ses-01_acq-inv1_T1map.json
sub-F113_ses-01_acq-inv1_T1map.nii.gz
sub-F113_ses-01_acq-uni_T1map.nii.gz
sub-F113_ses-01_acq-uni_T1map.json
sub-F113_ses-01_acq-mp2rage_T1map.nii.gz
sub-F113_ses-01_acq-mp2rage_T1map.json
sub-F113_ses-01_T1w.nii.gz
sub-F113_ses-01_T1w.json

command:
singularity run --cleanenv \
-B /storage/projects/neuroVFN/qMRI:/bids_dataset \
-B /storage/projects/neuroVFN/qMRI/derivatives/mica023:/output_directory \
-B /storage/brno2/home/pe_so/cert/license.txt:/cert \
-B $SCRATCHDIR:/tmp \
/storage/brno2/home/pe_so/sing_images/mica_v023.sif \
-bids /bids_dataset \
-out /output_directory \
-sub sub-F113 \
-ses 01 \
-proc_structural \
-uni \
-mf 45 \
-proc_surf \
-fs_licence /cert \
-post_structural \
-QC_subj

**Comment by rcruces** [comment]
Hello,

The error you're encountering is related to how the images are handled when the `-uni` flag is selected. This flag should be used together with the `-T1wStr` option (for specifying T1w strings). If `-T1wStr` is not provided, the pipeline defaults to using all T1w images in the `anat` directory.

In your case the default behavior is using the following images:

```bash
sub-F113_ses-01_space-nativepro_T1w_reo.nii.gz 
sub-F113_ses-01_acq-inv1_T1map.nii.gz 
sub-F113_ses-01_acq-inv2_T1map.nii.gz 
sub-F113_ses-01_space-nativepro_T1w_n4.nii.gz
```


To resolve this, you should specify the `-T1wStr` string like this:  
`-T1wStr UNI,INV1,INV2`

The order must be `UNI`, then `INV1`, and then `INV2`. In your case, it should be:  
`-T1wStr acq-uni_T1map,acq-inv1_T1map,acq-inv2_T1map`.

This specific case is under-documented, and we apologize for the confusion. We will include more detailed examples in our documentation going forward.

Let us know if you need further assistance!
