### ISSUE TITLE
-QC_subj does not produce QC report for dwi due to outdated json path

### ISSUE THREAD

**Issue by ajschadler12** [MICA-MNI/micapipe#88]
The `-QC_subj` workflow is unable to create a QC report for `-proc_dwi`, due to an outdated path being used for the preproc_dwi.json file:

```python
Traceback (most recent call last):
  File "/opt/micapipe/functions/QC.py", line 1658, in <module>
    static_report = qc_module_function['functions'][i](j)
  File "/opt/micapipe/functions/QC.py", line 839, in qc_proc_dwi
    with open( preproc_dwi_json ) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hamilton/locipipe_testing/derivatives/micapipe_v0.2.0/sub-test123/ses-01/dwi/sub-test123_ses-01_desc-preproc_dwi.json'
```

**Comment by rcruces** [comment]
Hello, this issue was addressed in the lates version v0.2.2 which is already available at dockerhub https://hub.docker.com/r/micalab/micapipe/tags

Thank you!
